name: CI

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        perl-version: [ '5.14', '5.36' ] 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl-version }}

      - name: Install dependencies
        run: |
          cpanm --installdeps --notest .
          cpanm --quiet --notest Test::More
          perl Makefile.PL

      - name: Run tests
        run: |
          make test